// frontend-vue/src/components/RoleDialog.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Loader2 } from 'lucide-vue-next'
import { useCreateRole, useUpdateRole } from '@/composables/useApi'
import { toast } from 'vue-sonner'

const props = defineProps<{
  role?: any
  permissions: any[]
}>()

const isEdit = computed(() => !!props.role)
const isOpen = ref(false)

const formData = ref({
  name: props.role?.name || '',
  description: props.role?.description || '',
  permissions: props.role?.permissions?.map((p: any) => p.permission.id) || [] as string[]
})

watch(() => props.role, (newVal) => {
  if (newVal) {
    formData.value = {
      name: newVal.name || '',
      description: newVal.description || '',
      permissions: newVal.permissions?.map((p: any) => p.permission.id) || []
    }
  } else {
    formData.value = { name: '', description: '', permissions: [] }
  }
}, { deep: true })

const { mutateAsync: createRole, isPending: isCreating } = useCreateRole()
const { mutateAsync: updateRole, isPending: isUpdating } = useUpdateRole()
const isSubmitting = computed(() => isCreating.value || isUpdating.value)

const modules = computed(() => Array.from(new Set(props.permissions.map(p => p.module))))

const handleSubmit = async (e: Event) => {
  e.preventDefault()
  try {
    if (isEdit.value) {
      await updateRole({ id: props.role.id, data: formData.value })
      toast.success("Role updated successfully")
    } else {
      await createRole(formData.value)
      toast.success("Role created successfully")
      formData.value = { name: '', description: '', permissions: [] }
    }
    isOpen.value = false
  } catch (err: any) {
    console.error(err)
    toast.error(err.message || "Failed to save role")
  }
}
</script>

<template>
  <Dialog v-model:open="isOpen">
    <DialogTrigger asChild>
      <slot />
    </DialogTrigger>
    <DialogContent class="sm:max-w-[600px] h-[80vh] flex flex-col bg-slate-900 border-slate-800 text-slate-50">
      <DialogHeader>
        <DialogTitle>{{ isEdit ? 'Edit Role' : 'Create Role' }}</DialogTitle>
        <DialogDescription class="text-slate-400">
          {{ isEdit ? 'Update the role details and permissions.' : 'Define a new role and assign its access levels.' }}
        </DialogDescription>
      </DialogHeader>

      <div class="flex-1 overflow-y-auto pr-2 custom-scrollbar">
        <form id="role-form" @submit="handleSubmit" class="space-y-6">
          <div class="space-y-4">
            <div class="grid gap-2">
              <Label for="role-name" class="text-slate-300">Role Name *</Label>
              <Input
                id="role-name"
                v-model="formData.name"
                class="bg-slate-800 border-slate-700 focus-visible:ring-indigo-500"
                placeholder="e.g. Regional Manager"
                required
              />
            </div>
            <div class="grid gap-2">
              <Label for="role-desc" class="text-slate-300">Description</Label>
              <Input
                id="role-desc"
                v-model="formData.description"
                class="bg-slate-800 border-slate-700 focus-visible:ring-indigo-500"
                placeholder="e.g. Manages operations for a specific region"
              />
            </div>
          </div>

          <div class="space-y-3">
            <Label class="text-slate-300 text-base">Permissions</Label>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div v-for="module in modules" :key="module" class="bg-slate-950/50 rounded-lg p-4 border border-slate-800/50">
                <h4 class="text-sm font-semibold text-slate-300 mb-3 pb-2 border-b border-slate-800">{{ module }}</h4>
                <div class="space-y-2">
                  <div v-for="p in permissions.filter(p => p.module === module)" :key="p.id" class="flex items-center space-x-2">
                    <input 
                      type="checkbox" 
                      :id="`perm-${p.id}`" 
                      :value="p.id"
                      v-model="formData.permissions"
                      class="rounded border-slate-700 bg-slate-800 text-indigo-500 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 cursor-pointer" 
                    />
                    <label
                      :for="`perm-${p.id}`"
                      class="text-xs font-medium leading-none text-slate-400 cursor-pointer select-none"
                    >
                      {{ p.name.split(':')[0] }}
                    </label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>

      <DialogFooter class="pt-4 border-t border-slate-800 mt-auto">
        <Button type="submit" form="role-form" :disabled="isSubmitting" class="bg-indigo-600 hover:bg-indigo-700 text-white">
          <Loader2 v-if="isSubmitting" class="mr-2 h-4 w-4 animate-spin" />
          {{ isEdit ? 'Save Changes' : 'Create Role' }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// frontend/src/components/RoleDialog.tsx
import { useState } from "react"
import { useStore } from "../store"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Loader2 } from "lucide-react"
import { toast } from "sonner"

export function RoleDialog({ role, children, permissions }: { role?: any, children: React.ReactNode, permissions: any[] }) {
  const { createRole, updateRole } = useStore()
  const isEdit = !!role
  const [isOpen, setIsOpen] = useState(false)
  const [formData, setFormData] = useState({
    name: role?.name || '',
    description: role?.description || '',
    permissions: role?.permissions?.map((p: any) => p.permission.id) || []
  })
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    try {
      if (isEdit) {
        await updateRole(role.id, formData)
        toast.success("Role updated successfully")
      } else {
        await createRole(formData)
        toast.success("Role created successfully")
      }
      setIsOpen(false)
      if (!isEdit) {
        setFormData({ name: '', description: '', permissions: [] })
      }
    } catch (err) {
      console.error(err)
      toast.error("Failed to save role")
    } finally {
      setIsSubmitting(false)
    }
  }

  const togglePermission = (permId: string) => {
    setFormData(prev => ({
      ...prev,
      permissions: prev.permissions.includes(permId)
        ? prev.permissions.filter((id: string) => id !== permId)
        : [...prev.permissions, permId]
    }))
  }

  const modules = Array.from(new Set(permissions.map(p => p.module)))

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px] h-[80vh] flex flex-col bg-slate-900 border-slate-800 text-slate-50">
        <DialogHeader>
          <DialogTitle>{isEdit ? 'Edit Role' : 'Create Role'}</DialogTitle>
          <DialogDescription className="text-slate-400">
            {isEdit ? 'Update the role details and permissions.' : 'Define a new role and assign its access levels.'}
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar">
          <form id="role-form" onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="name" className="text-slate-300">Role Name *</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="bg-slate-800 border-slate-700 focus-visible:ring-indigo-500"
                  placeholder="e.g. Regional Manager"
                  required
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="description" className="text-slate-300">Description</Label>
                <Input
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="bg-slate-800 border-slate-700 focus-visible:ring-indigo-500"
                  placeholder="e.g. Manages operations for a specific region"
                />
              </div>
            </div>

            <div className="space-y-3">
              <Label className="text-slate-300 text-base">Permissions</Label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {modules.map(module => (
                  <div key={module} className="bg-slate-950/50 rounded-lg p-4 border border-slate-800/50">
                    <h4 className="text-sm font-semibold text-slate-300 mb-3 pb-2 border-b border-slate-800">{module}</h4>
                    <div className="space-y-2">
                      {permissions.filter(p => p.module === module).map(p => (
                        <div key={p.id} className="flex items-center space-x-2">
                          <Checkbox
                            id={`perm-${p.id}`}
                            checked={formData.permissions.includes(p.id)}
                            onCheckedChange={() => togglePermission(p.id)}
                            className="border-slate-600 data-[state=checked]:bg-indigo-500 data-[state=checked]:border-indigo-500"
                          />
                          <label
                            htmlFor={`perm-${p.id}`}
                            className="text-xs font-medium leading-none text-slate-400 cursor-pointer select-none"
                          >
                            {p.name.split(':')[0]}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </form>
        </div>

        <DialogFooter className="pt-4 border-t border-slate-800 mt-auto">
          <Button type="submit" form="role-form" disabled={isSubmitting} className="bg-indigo-600 hover:bg-indigo-700 text-white">
            {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
            {isEdit ? 'Save Changes' : 'Create Role'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
